rootProject.name = "HencoderPlus"

include(":Jetpack:viewmodel")
include(":Jetpack:roomsample")
include(":Jetpack:coroutine")
include(":Jetpack:livedata")
include(":Jetpack:viewBinding")
include(":Jetpack:lifecycle")
include(":Jetpack:appstartup")
include(":Jetpack:workmanagersample")



include(":Inject:koinsample")
//include(":Inject:hiltsample")
include(":Inject:daggersample")


/**======HenCoder Plus======**/
include(":hencoder:1_http")
include(":hencoder:2_encrypt")
include(":hencoder:3_author")
include(":hencoder:4_tcpip")
include(":hencoder:4_retrofit")
include(":hencoder:5_retrofit")
include(":hencoder:5_kotlin")
include(":hencoder:6_okhttp")
include(":hencoder:9_kolitn")
include(":hencoder:10_drawing")
include(":hencoder:11_animator")
include(":hencoder:12_drawable")
include(":hencoder:13_layout")
include(":hencoder:14_touch")
include(":hencoder:15_scalableimageview")
include(":hencoder:16_multitouch")
include(":hencoder:16_multitouch1")
include(":hencoder:17_recyclerviewcore")
include(":hencoder:18_constraintlayout")
include(":hencoder:19_motionlayout")
include(":hencoder:20_viewpager")
include(":hencoder:21_drag_nestedscroll")
include(":hencoder:22_thread")
include(":hencoder:22_Thread_interaction")
include(":hencoder:23_rxjava")
include(":hencoder:24_io")
include(":hencoder:25_gradle")
include(":hencoder:28_plugin")
include(":hencoder:28_plugin_lib")
include(":hencoder:29_hotfix")
include(":hencoder:30_annotation")
include(":hencoder:30_annotation_reflection")
include(":hencoder:30_lib")
include(":hencoder:30_lib_annotation")
include(":hencoder:30_lib_processos")
include(":hencoder:31_generics")
include(":hencoder:32_view_draw_process")
include(":hencoder:33_hashmap")
include(":hencoder:34_gradle_process")
include(":hencoder:35_jvm")
include(":hencoder:36_window_inserts")


/**======compose======**/
include(":compose:todo")
include(":compose:01_hellocompose")
include(":compose:02_sample")
include(":compose:03_state")
